# BEDASSLE Analysis Configuration

# Define the output prefix
out_prefix: "results/BEDASSLE_champion_noLD"

# Input Files
vcf: "../../1-VariantCallFilt/07_freebayes/Paxil_M095_noLD.recode.vcf.gz"
popmap: "../../Paxil_PopGroupMap.csv"
env_dist: "../EnvironValriables/champion_EnvironVars_Selected_Distances.csv"

# BEDASSLE MCMC Execution Parameters
threads: 14
ngen: 2000000
printfreq: 10000
savefreq: 100000
samplefreq: 250
delta: 1e-20
aD_stp: 0.075
aE_stp: 0.05
a2_stp: 0.025
phi_stp: 30
thetas_stp: 0.2
mu_stp: 0.35
