# GLMM Analysis Configuration

# Define the output prefix (can include a subdirectory, e.g., "results/run_1")
out_prefix: "results/GLMM_champion_Paxil_PutatOutlier_BayeScEnv"

# Input Files
vcf: "../../2-OutlierDetection/Paxil_M095_PutatOutlier_BayeScEnv.recode.vcf.gz"
popmap: "../../Paxil_PopGroupMap.csv"
env_dist: "../EnvironValriables/champion_EnvironVars_Selected_Distances.csv"

# Execution Flags
run_indiv_loci: true

# GLMM MCMC Parameters
threads: 14
n_ger: 2000000
burnin: 500000
thin: 750
